studentsprofile/urls.py
from django.conf.urls import include ,url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<profile_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create_profile/$', views.create_profile, name='create_profile'),
    url(r'^(?P<profile_id>[0-9]+)/delete_profile/$', views.delete_profile, name='delete_profile'),
    url(r'^(?P<profile_id>[0-9]+)/create_detail/$', views.create_detail, name='create_detail'),
    url(r'^(?P<profile_id>[0-9]+)/delete_detail/(?P<detail_id>[0-9]+)/$', views.delete_detail, name='delete_detail'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^log_detail/(?P<filter_by>[a-zA_Z]+)/$', views.log_detail, name='log_detail')
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from studentsprofile import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^studentsprofile', include('studentsprofile.urls')),

    url(r'^$', views.index, name='index'),
    url(r'^(?P<profile_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create_profile/$', views.create_profile, name='create_profile'),
    url(r'^(?P<profile_id>[0-9]+)/delete_profile/$', views.delete_profile, name='delete_profile'),
    url(r'^(?P<profile_id>[0-9]+)/create_detail/$', views.create_profile, name='create_detail'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^log_detail/(?P<filter_by>[a-zA_Z]+)/$', views.log_detail, name='log_detail'),
]

studentsprofile/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


class Profile(models.Model):
    user = models.ForeignKey(User, default=1)
    email = models.CharField(max_length=100)
    fname = models.CharField(max_length=50)
    mname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50)

    def __str__(self):
        return self.lname + ' , ' + self.fname + ' ' + self.mname + '.'

class Details(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    gender = models.CharField(max_length=250)
    birthday = models.CharField(max_length=250)
    address = models.TextField()
    profile_logo = models.FileField()

    def __str__(self):
        return self.profile

studentsprofile/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile, Details


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['email', 'fname', 'mname', 'lname']


class DetailForm(forms.ModelForm):

    class Meta:
        model = Details
        fields = ['gender', 'birthday','address','profile_logo']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

studentsprofile/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import ProfileForm, DetailForm, UserForm
from .models import Profile, Details

IMAGE_FILE_TYPES = ['png','jpg','jpeg']

def index(request):
    if not request.user.is_authenticated():
        return render(request, 'studentsprofile/login.html')
    else:
        profiles = Profile.objects.filter(user=request.user)
        detail_result = Details.objects.all()
        query = request.GET.get("q")
        if query:
            profiles = profiles.filter(
                Q(email__icontains=query)
            ).distinct()
            detail_result = detail_result.filter(
                Q(detail_result__icontains=query)
            ).distinct()
            return render(request, 'studentsprofile/index.html', {
                'profiles': profiles,
                'details': detail_result,
            })
        else:
            return render(request, 'studentsprofile/index.html', {'profiles': profiles})

def detail(request, profile_id):
    form = DetailForm(request.POST or None, request.FILES or None)
    profile = get_object_or_404(Profile, pk=profile_id)
    if form.is_valid():
        profile = Profile._meta.all()
        for s in profile:
            if s.profile_id == form.cleaned_data.get("profile"):
                context = {
                    'profile': profile,
                    'form': form,
                    'error_message': 'You already added that profile',
                }
                return render(request, 'studentsprofile/create_detail.html', context)
    context = {
        'profile': profile,
        'form': form,
    }
    return render(request, 'studentsprofile/create_detail.html', context)


def create_profile(request):
    if not request.user.is_authenticated():
        return render(request, 'studentsprofile/login.html')
    else:
        form = ProfileForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.profile_logo = request.FILES['profile_logo']
            file_type = profile.profile_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'profile': profile,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'studentsprofile/create_profile.html', context)
            profile.save()
            return render(request, 'studentsprofile/detail.html', {'profile': profile})
        context = {
            "form": form,
        }
        return render(request, 'studentsprofile/create_profile.html', context)

def create_detail(request, profile_id):
    form = DetailForm(request.POST or None, request.FILES or None)
    profile = get_object_or_404(Profile, pk=profile_id)
    if form.is_valid():
        profiles_songs = profile.details_set.all()
        for s in profiles_songs:
            if s.profile_id == form.cleaned_data.get("profile_id"):
                context = {
                    'profile': profile,
                    'form': form,
                    'error_message': 'Already added this Profile',
                }
                return render(request, 'studentsprofile/create_detail.html', context)
        details = form.save(commit=False)
        details.profile = profile


def delete_profile(request, profile_id):
    profile = Profile.objects.get(pk=profile_id)
    profile.delete()
    profile = Profile.objects.filter(user=request.user)
    return render(request, 'studentsprofile/index.html', {'profile': profile})


def delete_detail(request, profile_id, detail_id):
    profile = get_object_or_404(Profile, pk=profile_id)
    details = Details.objects.get(pk=detail_id)
    details.delete()
    return render(request, 'studentsprofile/detail.html', {'profile': profile})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'studentsprofile/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                profiles = Profile.objects.filter(user=request.user)
                return render(request, 'studentsprofile/index.html', {'profile': profiles})
            else:
                return render(request, 'studentsprofile/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'studentsprofile/login.html', {'error_message': 'Invalid login'})
    return render(request, 'studentsprofile/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                profiles = Profile.objects.filter(user=request.user)
                return render(request, 'studentsprofile/index.html', {'profile': profiles})
    context = {
        "form": form,
    }
    return render(request, 'studentsprofile/register.html', context)

def log_detail(request, profile_id):
    if not request.user.is_authenticated():
        return render(request, 'studentsprofile/login.html')
    else:
        user = request.user
        profile = get_object_or_404(Profile, pk=profile_id)
        return render(request, 'studentsprofile/log_detail.html', {'profile': profile, 'user': user})

studentsprofile/templates/studentsprofile/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Prood{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static '/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:index' %}">Prood</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block profile_active %}{% endblock %}"><a href="{% url 'home:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Profile</a></li>
                <li class="{% block detail_active %}{% endblock %}"><a href="{% url 'home:log_detail' 'all'  %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Details</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'home:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'home:create_profile' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Profile
                    </a>
                </li>
                <li>
                    <a href="{% url 'home:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>
</title>
</head>
<body>

</body>
</html>

studentsprofile/templates/studentsprofile/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Prood{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static '/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:index' %}">Prood</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'home:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'home:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

studentsprofile/templates/studentsprofile/create_detail.html
{% extends 'studentsprofile/base.html' %}
{% block title %}{{ profile }}{% endblock %}
{% block profile_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'home:detail' profile.id %}">
                        {% if profile.profile_logo%}
                            <img src="{{ profile.profile_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h2>{{ profile.lname }} ,{{ profile.fname }} {{ profile.mname }}</h2>
                </div>
            </div>
        </div>

        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'home:detail' profile.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'home:create_detail' profile.id %}">Add New Detail</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Profile</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Gender</th>
                            <th>Birthday</th>
                            <th>Address</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for detail in profile.details_set.all %}
                            <tr>
                                <td>{{ detail.gender }}</td>
                                <td>{{ detail.birthday }}</td>
                                <td>{{ detail.address }}</td>
                                <td>{{ Action }}</td>
                                <td>
                                    <form action="{% url 'home:delete_profile' profile.id detail.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="profile_id" value="{{ detail.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}
</title>
</head>
<body>

</body>
</html>

studentsprofile/templates/studentsprofile/create_profile.html
{% extends 'studentsprofile/base.html' %}
{% block title %}Add a New Detail{% endblock %}
{% block profile_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'profile:detail' profile.id %}">
                            {% if profile.profile_logo %}
                                <img src="{{ profile.profile_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ profile.fname }} <small>{{ profile.mname}}</small></h1>
                    <h2>{{ profile.lname }}</h2>
                </div>
            </div>
        </div>

        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'profile:detail' profile.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'profile:create_profile' profile.id %}">Add New Profile/a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Profile</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="profile" value="{{ Profile }}">
                        {% include 'studentsprofile/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

studentsprofile/templates/studentsprofile/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="profile_id">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

studentsprofile/templates/studentsprofile/index.html
{% extends 'studentsprofile/base.html' %}
{% block profile_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Profiles</h3>
        </div>
        {% if profiles %}
            {% for profile in profiles %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'home:detail' profile.id %}">
                            <img src="{{ profile.profile_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ profile.fname}}</h2>
                            <h4>{{ profile.lname }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'home:detail' profile.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Profile -->
                            <form action="{% url 'home:delete_profile' profile.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="profile_id" value="{{ profle.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'home:create_profile' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add Profile
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    {% if details %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Detail</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Gender</th>
                                    <th>Birthday</th>
                                    <th>Address</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for detail in details %}
                                    <tr>
                                        <td>{{ detail.gender}}</td>
                                        <td>
                                            {{ detail.birthday }}</td>
                                        <td>
                                            {{ detail.address }}</td>
                                        <td>
                                        <form action="{% url 'home:delete_profile' profile.id detail.id %}" method="post" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="profile_id" value="{{ detail.id }}" />
                                            <button type="submit" class="btn btn-danger btn-xs">
                                                <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                            </button>
                                        </form>
                                    </td>
                                    </tr>

                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

studentsprofile/templates/studentsprofile/log_detail.html
{% extends 'studentsprofile/base.html' %}
{% block title %}{{ profile }}{% endblock %}
{% block profile_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'home:log_detail' profile.id %}">
                        {% if profile.profile_logo%}
                            <img src="{{ profile.profile_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ profile.fname}} <small>{{ profile.mname}}</small></h1>
                    <h2>{{ profile.lname}}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'home:log_detail' profile.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'home:create_detail' profile.id %}">Add New Detail</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Detail</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Gender</th>
                            <th>Birthday</th>
                            <th>Address</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for detail in profile.profile_set.all %}
                            <tr>
                                <td>{{ profile.fname }}</td>
                                    <form action="{% url 'home:delete_detail' profile.id detail.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="profile_id" value="{{ profile.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

studentsprofile/templates/studentsprofile/login.html
{% extends 'studentsprofile/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'home:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'home:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

studentsprofile/templates/studentsprofile/register.html
{% extends 'studentsprofile/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'studentsprofile/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'home:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}